#define WUXD Windows.UI.Xaml.Data

namespace mvvm.tests
{
    [default_interface]
    runtimeclass StringToInt32ValueConverter : WUXD.IValueConverter
    {
        StringToInt32ValueConverter();
    }
}
